require "pears".setup(function(conf)
  conf.pair("{", "}")
  conf.pair("(", ")")
  conf.pair("\\(", "\\)")
  conf.pair("\\[", "\\]")
  conf.pair("'", "'")
  conf.pair('"', '"')
  conf.expand_on_enter(false)
end)
