default:
    extension: .config
    output: themes

bar-colors:
    extension: .config
    output: bar-colors

client-properties:
    extension: .config
    output: client-properties

colors:
    extension: .config
    output: colors
