#! /bin/sh

### Autostart ###
sxhkd &
picom --config ~/.config/picom/picom.conf &
nitrogen --restore &
$HOME/.config/polybar/launch.sh &
espanso start &
killall -9 flameshot
flameshot &
redshift -x
killall -9 redshift
redshift &
dunst &
pgrep bspswallow || bspswallow &
xsetroot -cursor_name left_ptr &

### Monitors ###
bspc monitor DVI-D-0 -d 1 2 3 4 5 6 7 8 9

### BSPWM Configuration ###
bspc config border_width 2
bspc config window_gap 10
bspc config top_padding 20
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0
bspc config single_monocle false
bspc config click_to_focus true
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true
bspc config focus_follows_pointer true
bspc config history_aware_focus true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config pointer_motion_interval 7

### Colouring ###
bspc config normal_border_color $(xrdb -q | grep color0 | awk '{print $2}')
bspc config active_border_color $(xrdb -q | grep color0 | awk '{print $2}')
bspc config focused_border_color $(xrdb -q | grep accent | awk '{print $2}')
bspc config presel_feedback_color $(xrdb -q | grep accent | awk '{print $2}')
bspc config urgent_border_color $(xrdb -q | grep color1 | awk '{print $2}')

#polybar hidden when fullscreen for vlc, youtube, mpv, etc.
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_eDP-1)

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Wine:photoshop.exe state=floating

# fix jetbrains software
wmname LG3D
