#! /bin/sh

#################
### Autostart ###
#################

sxhkd &
picom &
nitrogen --restore &
$HOME/.config/polybar/launch.sh &
espanso start &
killall -9 flameshot
flameshot &
redshift -x; killall -9 redshift; redshift &
# eww daemon &
dunst &
pgrep bspswallow || bspswallow &
xsetroot -cursor_name left_ptr &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/lib/kdeconnectd &
kdeconnect-indicator &

################
### Monitors ###
################

# bspc monitor DVI-D-0 -d 1 2 3 4 5 6 7 8 9
bspc monitor DP-0 -d 1 2 3 4 5 6 7 8 9

###########################
### BSPWM Configuration ###
###########################

bspc config border_width 2
bspc config window_gap 10
bspc config top_padding 37
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0
bspc config single_monocle false
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
# bspc config focus_by_distance true
bspc config focus_follows_pointer true
bspc config history_aware_focus true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config pointer_motion_interval 7

#################
### Colouring ###
#################

# start flavours
bspc config normal_border_color 	\#191724
bspc config active_border_color 	\#191724
bspc config focused_border_color 	\#c4a7e7
bspc config presel_feedback_color 	\#c4a7e7
bspc config urgent_border_color 	\#eb6f92
# end flavours

#############
### Rules ###
#############

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled
bspc rule -a Wine:photoshop.exe state=floating
bspc rule -a feh state=floating
bspc rule -a firefox:Toolkit state=floating sticky=on

#####################
### Floating Size ###
#####################

x=$(xwininfo -root | grep Width | awk '{print $2}')
y=$(xwininfo -root | grep Height | awk '{print $2}')

# bspc rule -a firefox center=true rectangle=${$((0.6 * x))%.}x${$((0.6 * y))%.}+0+0
bspc rule -a firefox:Navigator center=true rectangle=1280x720+0+0
# bspc rule -a kitty center=true rectangle=${$((0.36 * x))%.}x${$((0.3 * y))%.}+0+0
bspc rule -a kitty center=true rectangle=700x400+0+0

############
### Misc ###
############

# polybar hidden when fullscreen for vlc, youtube, mpv, etc.
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DVI-D-0)

# fix jetbrains software
wmname LG3D
