# start flavours
[colors.bright]
black   = '0x45475a'
red     = '0xf38ba8'
green   = '0xa6e3a1'
yellow  = '0xfab387'
blue    = '0x89b4fa'
magenta = '0xcba6f7'
cyan    = '0x94e2d5'
white   = '0xe2e1e7'

[colors.normal]
black   = '0x191724'
red     = '0xf38ba8'
green   = '0xa6e3a1'
yellow  = '0xf9e2af'
blue    = '0x89b4fa'
magenta = '0xcba6f7'
cyan    = '0x94e2d5'
white   = '0xcdd6f4'

[colors.cursor]
text = '0x191724'
cursor = '0xcdd6f4'

[colors.primary]
background = '0x191724'
foreground = '0xcdd6f4'

[[colors.indexed_colors]]
color = "0xfab387"
index = 16

[[colors.indexed_colors]]
color = "0xf2cdcd"
index = 17

[[colors.indexed_colors]]
color = "0x181825"
index = 18

[[colors.indexed_colors]]
color = "0x313244"
index = 19

[[colors.indexed_colors]]
color = "0x585b70"
index = 20

[[colors.indexed_colors]]
color = "0xe0def4"
index = 21
# end flavours

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"
mods = "None"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"
mods = "None"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "K"
mode = "~Alt"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "J"
mode = "~Alt"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "G"
mode = "~Alt"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "None"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "None"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[scrolling]
history = 10000

[window]
dynamic_padding = false
opacity = 1.0
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 12
y = 12
